import type { Metadata } from "next";
import { Outfit, Space_Grotesk } from "next/font/google";
import "./globals.css";
import { cn } from "@dookdiks/utils";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";

const outfit = Outfit({ variable: "--font-outfit", subsets: ["latin"] });
const spaceGrotesk = Space_Grotesk({
	variable: "--font-space-grotesk",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default async function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = cookies();
	const session = cookieStore.get("cpe_space_session");
	const userId = cookieStore.get("user-id");

	console.log({ session, userId });
	return (
		<html lang="en">
			<body
				className={cn(
					outfit.variable,
					spaceGrotesk.variable,
					"font-sans bg-liberty min-h-screen"
				)}
			>
				{children}
			</body>
		</html>
	);
}
