import type { Metadata } from 'next';
import { Outfit, Space_Grotesk } from 'next/font/google';
import './globals.css';
import { cn } from '@dookdiks/utils';
import { cookies } from 'next/headers';
import MainLayout from './_components/mainLayout';
import { Suspense } from 'react';
import Loading from './loading';
import { IsProfile } from './_components/pathname';
import { usePathname } from 'next/navigation';

const outfit = Outfit({ variable: '--font-outfit', subsets: ['latin'] });
const spaceGrotesk = Space_Grotesk({
  variable: '--font-space-grotesk',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();

  const session = cookieStore.get('cpe_space_session');
  const user = cookieStore.get('user-id');
  const profile = cookieStore.get('profile');

  const isLogin = !!session?.value && !!user?.value;
  const isProfile = !!profile?.value;

  const IsSignIn = ({
    children,
    render,
  }: Readonly<{ children: React.ReactNode; render: React.ReactNode }>) => {
    return isLogin ? render : children;
  };

  return (
    <html lang="en">
      <body
        className={cn(
          outfit.variable,
          spaceGrotesk.variable,
          'font-sans bg-liberty min-h-dvh overflow-auto',
        )}
      >
        <Suspense fallback={<Loading />}>
          <IsSignIn
            render={
              <IsProfile render={children}>
                <MainLayout>{children}</MainLayout>
              </IsProfile>
            }
          >
            {children}
          </IsSignIn>
        </Suspense>
      </body>
    </html>
  );
}
